---
title: "regional analysis"
output: html_document
date: "2023-02-06"
---

```{r}
library(ggpubr)
library(GGally)
library(ggplot2)
```

```{r}
data <- read.csv("C:/Users/eepar/Desktop/miles_2019.csv")
library("ggpubr")
ggscatter(data, x = "mi_sqrt", y = "fert_sq", 
          add = "reg.line", conf.int = TRUE, conf.int.level = 0.95, 
          cor.coef = TRUE, cor.method = "spearman",
          xlab = "Mile distance between parent colony source", ylab = "Fertilization %", main= "2019 ACER: Mile Distance Between Parents vs Fertilization % (Pearson)")
```
```{r}
data <- read.csv("C:/Users/eepar/Desktop/miles_2022.csv")
library("ggpubr")
ggscatter(data, x = "mi", y = "fert", 
          add = "reg.line", conf.int = TRUE, conf.int.level = 0.95, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Mile distance between parent colony source", ylab = "Fertilization %", main= "2022 ACER: Mile Distance Between Parents vs Fertilization % (Pearson)")
```



```{r}
data <- read.csv("C:/Users/eepar/Downloads/acer3_miles.csv")
library("ggpubr")
ggscatter(data, x = "mi", y = "fert", 
          add = "reg.line", conf.int = TRUE, conf.int.level = 0.95, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Mile distance between parent colony source", ylab = "Fertilization %", main= "8/13/22 ACER: Mile Distance Between Parents vs Fertilization % (Pearson)", xlim=c(0,120))
```

```{r}
data <- read.csv("C:/Users/eepar/Downloads/acer4_miles.csv")
library("ggpubr")
ggscatter(data, x = "mi", y = "fert", 
          add = "reg.line", conf.int = TRUE, conf.int.level = 0.95, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Mile distance between parent colony source", ylab = "Fertilization %", main= "8/15/22 ACER: Mile Distance Between Parents vs Fertilization % (Pearson)",  xlim=c(0,120))
```






```{r}
data <- read.csv("C:/Users/eepar/Downloads/acer1_miles.csv")
library("ggpubr")
ggscatter(data, x = "mi", y = "fert", 
          add = "reg.line", conf.int = TRUE, conf.int.level = 0.95, 
          cor.coef = TRUE, cor.method = "spearman",
          xlab = "Mile distance between parent colony source", ylab = "Fertilization %", main= "8/22/19 ACER: Mile Distance Between Parents vs Fertilization % (Spearman)", xlim=c(0,120))
```


```{r}
data <- read.csv("C:/Users/eepar/Downloads/acer2_miles.csv")
library("ggpubr")
ggscatter(data, x = "mi", y = "fert", 
          add = "reg.line", conf.int = TRUE, conf.int.level = 0.95, 
          cor.coef = TRUE, cor.method = "spearman",
          xlab = "Mile distance between parent colony source", ylab = "Fertilization %", main= "8/23/19 ACER: Mile Distance Between Parents vs Fertilization % (Spearman)", xlim=c(0,120))
```

```{r}
data <- read.csv("C:/Users/eepar/Desktop/2019all_time.csv")
library("ggpubr")
ggscatter(data, x = "time", y = "fert", 
          add = "reg.line", conf.int = TRUE, conf.int.level = 0.95, 
          cor.coef = TRUE, cor.method = "spearman",
          xlab = "Gamete Age", ylab = "Fertilization %", main= "2019 ACER Gamete Age vs. Fertilization (Spearman)")
```

```{r}
data <- read.csv("C:/Users/eepar/Desktop/2022all_time.csv")
library("ggpubr")
ggscatter(data, x = "time", y = "fert", 
          add = "reg.line", conf.int = TRUE, conf.int.level = 0.95, 
          cor.coef = TRUE, cor.method = "spearman",
          xlab = "Gamete Age", ylab = "Fertilization %", main= "2022 ACER Gamete Age vs. Fertilization (Spearman)")
```